blend:
  common:
    num_blend_layers: 3
    minimum_network_size: 30
    protocol_name: /blend/integration-tests
    data_replication_factor: 0
  core:
    scheduler:
      cover:
        message_frequency_per_round: 1.0
        intervals_for_safety_buffer: 100
      delayer:
        maximum_release_delay_in_rounds: 3
    minimum_messages_coefficient: 1
    normalization_constant: 1.03
    activity_threshold_sensitivity: 1
network:
  kademlia_protocol_name: /integration/logos-blockchain/kad/1.0.0
  identify_protocol_name: /integration/logos-blockchain/identify/1.0.0
  chain_sync_protocol_name: /integration/logos-blockchain/chainsync/1.0.0
cryptarchia:
  epoch_config:
    epoch_stake_distribution_stabilization: 3
    epoch_period_nonce_buffer: 3
    epoch_period_nonce_stabilization: 4
  security_param: 20
  slot_activation_coeff:
    numerator: 1
    denominator: 10
  learning_rate: 0.1
  sdp_config:
    service_params:
      BN:
        lock_period: 10
        inactivity_period: 1
        retention_period: 1
        timestamp: 0
    min_stake:
      threshold: 1
      timestamp: 0
  gossipsub_protocol: /integration/logos-blockchain/cryptarchia/proto/1.0.0
  genesis_state:
    mantle_tx:
      ops:
        - opcode: 0
          payload:
            inputs: [ ]
            outputs:
              - value: 1
                pk: d204000000000000000000000000000000000000000000000000000000000000
              - value: 100
                pk: 2e03b2eff5a45478e7e79668d2a146cf2c5c7925bce927f2b1c67f2ab4fc0d26
        - opcode: 17
          payload:
            channel_id: "0000000000000000000000000000000000000000000000000000000000000000"
            inscription: [ 103, 101, 110, 101, 115, 105, 115 ]  # "genesis" in bytes
            parent: "0000000000000000000000000000000000000000000000000000000000000000"
            signer: "0000000000000000000000000000000000000000000000000000000000000000"
      execution_gas_price: 0
      storage_gas_price: 0
    ops_proofs:
      - !ZkSig
        pi_a: [
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        ]
        pi_b: [
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        ]
        pi_c: [
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        ]
      - NoProof
time:
  slot_duration: '1.0'
  chain_start_time: 2026-02-17 07:47:56.891858 +00:00:00
mempool:
  pubsub_topic: mantle_e2e_tests
